version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py wait_for_db &&
             python3 manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASSWORD=supersecretpassword
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
    ports:
      - "5432:5432"

  qcluster:
    build: .
    command: sh -c "python manage.py qcluster && redis-cli"
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - DB_HOST=redis
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASSWORD=supersecretpassword


  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"

  redis:
    image: redis
    ports:
      - "6379:6379"